#! /bin/sh

# AutoStart
sxhkd &
~/.config/polybar/default/launch.sh &
compton --config ~/.config/compton/compton.conf &
dwall -s forest &

bspc monitor -d I II III IV V

bspc config border_width          1
bspc config window_gap            5

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config border_radius         0

bspc config normal_border_color "#$color8"
bspc config active_border_color "#$color9"
bspc config focused_border_color "#$color9"
bspc config presel_feedback_color "#$color1"

bspc rule -a google-chrome desktop='^2'

xsetroot -cursor_name left_ptr &
